name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show greeting
        run: echo "Salam DevSecOps! Workflow işə düşdü ✅"

      - name: Placeholder tests
        run: echo "Burada testlər işləyəcək..."
