name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (only if package.json exists)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        if: hashFiles('package.json') != ''
        run: npm install

      - name: Run tests
        if: hashFiles('package.json') != ''
        run: npm test

      - name: Dummy step (no Node project)
        if: hashFiles('package.json') == ''
        run: echo "No package.json — basic CI passed ✅"
