name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodun checkout edilməsi
      uses: actions/checkout@v4

    - name: Node.js quraşdır
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Asılılıqları yüklə
      run: npm install

    - name: Testləri işə sal
      run: npm test
